### ISSUE TITLE
create-index in clang.rkt crashes

### ISSUE THREAD

**Issue by parenthetical** [endobson/racket-llvm#5]
I'm trying to get racket-llvm up and running, but I'm getting crashes when trying to load the example programs. I've tracked the crash from `enums.rkt` to `read-header` to `create-index`. Once the inner allocator `create-index` here is called the whole process crashes:
```
(define create-index
  (let ()
    (define dispose-index
      (get-ffi-obj "clang_disposeIndex" lib-clang (_fun _pointer -> _void))) 
    (define create-index
      ((allocator dispose-index)
       (get-ffi-obj "clang_createIndex" lib-clang (_fun _bool _bool -> _pointer))) )
    
    (lambda (#:exclude-declarations-from-pch [exclude #f] #:display-diagnostics [diagnostics #f])
      (index (create-index exclude diagnostics)))))
```

I haven't been able to look at core dumps yet (not that I could find any, despite the "core dumped" message), but maybe someone might know what's up?

**Comment by endobson** [comment]
I'm about to be out for a trip for the next few days, so won't be able to look at until after that. But important things for debugging. What version of LLVM and OS are you using? I have only tested on OS X at the latest version of LLVM when a commit was made.

Also I just pushed two changes that were written months ago, one of which fixed a bug in `enums.rkt` so that might have been your issue.

**Comment by parenthetical** [comment]
No problem!

I'm on Ubuntu Trusty (14.04.2), and the issue occurs with both LLVM 3.5 and 3.6. All I have to do to trigger it is:
```
(require "private/llvm-headers.rkt")
(create-index)
```

The recent commits didn't change anything.

**Comment by endobson** [comment]
I got this working with ubuntu 15.04 and LLVM 3.6. I needed to deal with a bunch of issues with the setup looking in the wrong places for things, but no segfault.

**Comment by parenthetical** [comment]
Okay, so I updated my installation to 15.04 and installed llvm 3.6 (I did `apt-get install llvm-dev libclang-dev, and then fixed the paths in racket-llvm etc.)

I was hoping that the problem would go away after the upgrade but it didn't. Could you confirm that running the following program does not result in a crash?

```
#lang racket
(require "private/clang.rkt")
(create-index)
(displayln "here")
```

On my computer this does:
```
$ racket test.rkt
#<index>
aborted (core dumped)
```

However, the first time I tried it it took a longer time before crashing and it also evaluated the last expression:
```
$ racket test.rkt
#<index>
test
<a few seconds pass>
aborted (core dumped)
```

I haven't been able to replicate that since. Very strange.

**Comment by endobson** [comment]
The displayln crashes it. I'll see whats up.

**Comment by endobson** [comment]
3eb557b0fe4bddfdfce8e8f4659d218535daa061 should have fixed the issue.

**Comment by parenthetical** [comment]
Thanks, this did indeed fix the issue.
